# Generated by Django 4.1 on 2022-08-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receive_news',
            field=models.BooleanField(default=True),
        ),
    ]
