# Generated by Django 4.1 on 2022-08-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_receive_activity_customuser_receive_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cookie_policy_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
