# Generated by Django 4.1 on 2022-09-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verify_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
