# Generated by Django 4.1 on 2022-08-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_cookie_policy_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cookie_policy_accepted',
        ),
    ]
