# Generated by Django 4.1 on 2022-09-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_reset_password_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_password_code',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verify_code',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
