# Generated by Django 4.1 on 2022-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_image_id',
            field=models.IntegerField(default=1),
        ),
    ]
