# Generated by Django 4.1 on 2022-10-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('important_info', '0003_pagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmodel',
            options={'verbose_name': 'Faq settings', 'verbose_name_plural': 'Faq settings'},
        ),
        migrations.AlterModelOptions(
            name='pagemodel',
            options={'verbose_name': 'Page Seo Settings', 'verbose_name_plural': 'Pages Seo Settings'},
        ),
    ]
