# Generated by Django 4.1 on 2022-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_info', '0005_seotext_seotitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seotext',
            name='title',
        ),
        migrations.AddField(
            model_name='seotext',
            name='name_for_admin',
            field=models.CharField(default='default name', max_length=200),
        ),
    ]
