# Generated by Django 4.1 on 2022-09-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0014_alter_boardmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Google Analytics',
                'verbose_name_plural': 'Google Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.boardmodel',),
        ),
    ]
