# Generated by Django 4.1 on 2022-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_userstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='visitors_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
