# Generated by Django 4.1 on 2022-09-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_ordercalcmodel_total_integer'),
        ('analytics', '0003_alter_userstatistics_visitors_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAnalytics',
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.boardmodel',),
        ),
    ]
