# Generated by Django 4.1 on 2022-09-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
