# Generated by Django 4.1 on 2022-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_invoice_stripe_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
