# Generated by Django 4.1 on 2022-09-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_invoice_complete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='complete_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
