# Generated by Django 4.1 on 2022-12-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_invoice_complete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('CreditCard', 'CreditCard'), ('CoinBase', 'CreditCard')], max_length=50),
        ),
    ]
