# Generated by Django 4.1 on 2022-10-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_invoice_complete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cents',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
