"""
Django settings for dms_bulk_django project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

dotenv_path = os.path.join(os.path.dirname(__file__), '.env')
load_dotenv(dotenv_path)

SITE_ID = 1

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
SECURE_SSL_REDIRECT = False

ALLOWED_HOSTS = ['*']

# Application definition
AUTH_USER_MODEL = 'account.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'rest_framework',
    'admin_reorder',
    'mathfilters',
    'djstripe',
    'online_users',
    'paypal.standard.ipn',
    'home',
    'core',
    'account',
    'account_auth',
    'dashboard',
    'order',
    'blog',
    'payment',
    'analytics',
    'important_info'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
    'online_users.middleware.OnlineNowMiddleware',
    'account.middleware.VisitCounterMiddleware',
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dms',
        'USER': 'postgres',
        'PASSWORD': 'example',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

ROOT_URLCONF = 'dms_bulk_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dms_bulk_django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
]

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ]
# }

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, '/home/static')
MEDIA_URL = 'media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field


ADMIN_REORDER = (
    'sites',
    {'app': 'account', 'label': 'Accounts', 'models': ('account.CustomUser',)},
    {'app': 'blog', 'models': ('blog.ArticleModel',)},
    {'app': 'order', 'label': 'Board Settings', 'models': ('order.BoardModel', 'order.ServicesUnderMaintenance')},
    {'app': 'order', 'models': ('order.OrderCalcModel', 'order.OrderModel')},
    {'app': 'order', 'label': 'Coupons', 'models': ('order.Coupon',)},
    {'app': 'order', 'label': 'Invoices', 'models': ('payment.Invoice',)},
    {'app': 'analytics', 'models': ('analytics.Analytics',)},
    {'app': 'important_info', 'label': 'Frequently Asked Questions', 'models': ('important_info.FAQModel',)},
    {'app': 'home', 'models': ('home.PageModel',)},
    {'app': 'important_info', 'label': 'Seo', 'models': ('important_info.PageModel',)},
)
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = str(os.getenv('EMAIL_HOST'))
EMAIL_HOST_USER = str(os.getenv('EMAIL_HOST_USER'))
EMAIL_HOST_PASSWORD = str(os.getenv('EMAIL_HOST_PASSWORD'))
CELERY_SEND_MAIL_HOST = str(os.getenv('CELERY_SEND_MAIL_HOST'))

INVALID_DISCOUNT_MESSAGE = 'the entered discount value does not match the actual value mommy hacker'
INVALID_ORDER_AMOUNT_MESSAGE = 'the entered order amount value does not match the actual value mommy hacker'

STRIPE_LIVE_PUBLIC_KEY = str(os.getenv("STRIPE_LIVE_PUBLIC_KEY"))

STRIPE_LIVE_SECRET_KEY = str(os.getenv("STRIPE_LIVE_SECRET_KEY"))
STRIPE_TEST_PUBLIC_KEY = str(os.getenv("STRIPE_TEST_PUBLIC_KEY"))
STRIPE_TEST_SECRET_KEY = str(os.getenv("STRIPE_TEST_SECRET_KEY"))
STRIPE_LIVE_MODE = False
DJSTRIPE_WEBHOOK_SECRET = str(os.getenv("DJSTRIPE_WEBHOOK_SECRET"))
DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"

PAYPAL_TEST = True
PAYPAL_RECEIVER_EMAIL = str(os.getenv("PAYPAL_RECEIVER_EMAIL"))
PAYPAL_CLIENT_ID = str(os.getenv("PAYPAL_CLIENT_ID"))
try:
    from .local_settings import *
except ImportError:
    pass
