# Generated by Django 4.1 on 2022-09-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
