# Generated by Django 4.1 on 2022-09-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articlemodel_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='slug',
            field=models.CharField(default='article', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
