# Generated by Django 4.1 on 2022-08-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articlemodel_content_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ('-created_at',)},
        ),
    ]
