<<<<<<< HEAD
# Generated by Django 4.1 on 2022-08-30 18:03
=======
# Generated by Django 4.1 on 2022-08-31 14:38
>>>>>>> 4340a69fa26c0bb433759f1730ac7d6e8a10d4ad

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articlemodel_content_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ('-created_at',)},
        ),
    ]
