# Generated by Django 4.1 on 2022-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlemodel_slug_alter_articlemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='slug',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
