# Generated by Django 4.1 on 2022-09-30 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articlemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
