# Generated by Django 4.1 on 2022-10-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articlemodel_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Article', 'verbose_name_plural': 'Article'},
        ),
    ]
