from .tasks import generate_key
from .tasks import send_verify_link_to_email
from .tasks import send_reset_password_link_to_email
from .tasks import send_welcome_to_dmsbulk_message_after_success_verifing