# Generated by Django 4.1 on 2022-08-31 05:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_board_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('instagram_board_amount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('instagram_board_discount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('twitter_board_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('twitter_board_amount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('twitter_board_discount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('discord_board_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('discord_board_amount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('discord_board_discount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('telegram_board_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('telegram_board_amount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
                ('telegram_board_discount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=13)),
            ],
        ),
    ]
