# Generated by Django 4.1 on 2022-09-03 14:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_board_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('instagram_board_amount', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('instagram_board_discount', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('instagram_board_total', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('twitter_board_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('twitter_board_amount', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('twitter_board_discount', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('twitter_board_total', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('discord_board_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('discord_board_amount', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('discord_board_discount', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('discord_board_total', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('telegram_board_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('telegram_board_amount', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('telegram_board_discount', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('telegram_board_total', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCalcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Discord', 'Discord'), ('Telegram', 'Telegram')], max_length=9)),
                ('amount', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sending_end_at', models.DateTimeField(blank=True, null=True)),
                ('targets_or_competitors_submited', models.TextField(max_length=100000)),
                ('use_our_default_filtering', models.BooleanField()),
                ('not_use_any_filtering', models.BooleanField()),
                ('message', models.TextField(max_length=1000)),
                ('attach_in_message', models.TextField(max_length=600)),
                ('additional_information', models.TextField(max_length=600)),
                ('contact_details', models.CharField(max_length=1000)),
                ('scraping', models.BooleanField(default=False)),
                ('filtering', models.BooleanField(default=False)),
                ('sending', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('order_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordercalcmodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
