# Generated by Django 4.1 on 2022-08-31 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='discord_board_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=13),
        ),
        migrations.AlterField(
            model_name='board',
            name='instagram_board_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=13),
        ),
        migrations.AlterField(
            model_name='board',
            name='telegram_board_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=13),
        ),
        migrations.AlterField(
            model_name='board',
            name='twitter_board_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=13),
        ),
    ]
