# Generated by Django 4.1 on 2022-08-31 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='discord_board_total',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='board',
            name='instagram_board_total',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='board',
            name='telegram_board_total',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='board',
            name='twitter_board_total',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='discord_board_amount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='discord_board_discount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='discord_board_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='instagram_board_amount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='instagram_board_discount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='instagram_board_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='telegram_board_amount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='telegram_board_discount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='telegram_board_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='twitter_board_amount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='twitter_board_discount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='twitter_board_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
