# Generated by Django 4.1 on 2022-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='send_messages_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='sending_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
