# Generated by Django 4.1 on 2022-08-31 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_alter_board_discord_board_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='BoardModel',
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets_or_competitors_submited', models.TextField(max_length=100000)),
                ('use_our_default_filtering', models.BooleanField()),
                ('not_use_any_filtering', models.BooleanField()),
                ('message', models.TextField(max_length=100000)),
                ('attach_in_message', models.TextField(max_length=100000)),
                ('additional_information', models.TextField(max_length=100000)),
                ('contact_details', models.CharField(max_length=100000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
