# Generated by Django 4.1 on 2022-09-02 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_add_dafault_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCalcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Discord', 'Discord'), ('Telegram', 'Telegram')], max_length=9)),
                ('amount', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Board',
            new_name='BoardModel',
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('targets_or_competitors_submited', models.TextField(max_length=100000)),
                ('use_our_default_filtering', models.BooleanField()),
                ('not_use_any_filtering', models.BooleanField()),
                ('message', models.TextField(max_length=1000)),
                ('attach_in_message', models.TextField(max_length=600)),
                ('additional_information', models.TextField(max_length=600)),
                ('contact_details', models.CharField(max_length=1000)),
                ('scraping', models.BooleanField(default=False)),
                ('filtering', models.BooleanField(default=False)),
                ('sending', models.BooleanField(default=False)),
                ('sending_count', models.BigIntegerField(default=0)),
                ('order_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordercalcmodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
