# Generated by Django 4.1 on 2022-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordercalcmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercalcmodel',
            name='amount_integer',
            field=models.IntegerField(null=True),
        ),
    ]
