# Generated by Django 4.1 on 2022-09-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordercalcmodel_rename_board_boardmodel_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
