# Generated by Django 4.1 on 2022-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordercalcmodel_amount_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercalcmodel',
            name='amount_integer',
            field=models.IntegerField(default=0),
        ),
    ]
