# Generated by Django 4.1 on 2022-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordercalcmodel_amount_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
