# Generated by Django 4.1 on 2022-09-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordermodel_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='accepted',
        ),
    ]
