# Generated by Django 4.1 on 2022-09-16 16:28

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_remove_ordermodel_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercalcmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 16, 28, 23, 254844, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=1000)),
                ('discount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('number_of_uses', models.IntegerField(default=1)),
                ('user', models.ManyToManyField(related_name='coupon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
