# Generated by Django 4.1 on 2022-09-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_ordercalcmodel_created_at_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercalcmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
