# Generated by Django 4.1 on 2022-09-16 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_alter_ordercalcmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='coupon', to=settings.AUTH_USER_MODEL),
        ),
    ]
