# Generated by Django 4.1 on 2022-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
