# Generated by Django 4.1 on 2022-09-20 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0013_alter_ordercalcmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmodel',
            options={'verbose_name': 'Board Settings', 'verbose_name_plural': 'Board Settings'},
        ),
        migrations.AlterField(
            model_name='ordercalcmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_calc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_model', to='order.ordercalcmodel'),
        ),
    ]
