# Generated by Django 4.1 on 2022-09-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_ordercalcmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmodel',
            options={'verbose_name': 'Board Settings', 'verbose_name_plural': 'Board Settings'},
        ),
    ]
