# Generated by Django 4.1 on 2022-09-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_boardmodel_options_alter_ordercalcmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_calc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_model', to='order.ordercalcmodel'),
        ),
    ]
