# Generated by Django 4.1 on 2022-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_ordercalcmodel_total_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercalcmodel',
            name='total_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
