# Generated by Django 4.1 on 2022-09-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_ordercalcmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='hours_to_sending_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
