# Generated by Django 4.1 on 2022-09-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_add_default_services_under_maintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesundermaintenance',
            options={'verbose_name': 'ServicesUnderMaintenance', 'verbose_name_plural': 'ServicesUnderMaintenance'},
        ),
    ]
