# Generated by Django 4.1 on 2022-10-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_servicesundermaintenance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-created_at',), 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupon'},
        ),
        migrations.AlterModelOptions(
            name='ordercalcmodel',
            options={'verbose_name': 'Order Calc', 'verbose_name_plural': 'Order Calc'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
    ]
