# Generated by Django 4.1 on 2022-10-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_coupon_options_alter_ordercalcmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='additional_information',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='attach_in_message',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='contact_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='not_use_any_filtering',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='targets_or_competitors_submited',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='use_our_default_filtering',
            field=models.BooleanField(default=False),
        ),
    ]
