# Generated by Django 4.1 on 2022-10-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_ordermodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='attach_in_message',
            field=models.TextField(default='a', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='contact_details',
            field=models.CharField(default='q', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='message',
            field=models.TextField(default='s', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='targets_or_competitors_submited',
            field=models.TextField(default='w', max_length=100000),
            preserve_default=False,
        ),
    ]
